name: olySquads
main: com.olympuspvp.squads.olySquads
<<<<<<< HEAD
version: 2.1.4
=======
version: 2.2.1
>>>>>>> v2.2.1 - Fixed bug in TeleportListener and allowed people in creative mode to bypass it
author: CalDaBeast
description: Lightweight teaming plugin

commands:
    s:
        description: Manages olySquads
    squad:
        description: Manages olySquads